### ISSUE TITLE
phpStorm冲突

### ISSUE THREAD

**Issue by wuqiyin** [ahkohd/switch-desktop#29]
phpstorm的alt+1快捷键冲突了，导致无法使用alt+1

**Comment by ahkohd** [comment]
@wuqiyin Thanks for reaching out. Incase of key conflict, since you can't change Switch's Alt key there are two things you can do.
- Don't assign a app to Alt 1
- Check if you can change php storm Alt +1 to another key combo.
The second option seems reasonable.
Translation:

谢谢你伸出援手。由于您无法更改Switch的Alt键，因此您可以执行两项操作。
 - 不要将应用程序分配给Alt 1
 - 检查是否可以将php storm Alt +1更改为另一个关键组合。

第二种选择似乎是合理的。
